# Generated by Django 3.2.5 on 2021-07-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFileUpload', '0002_document_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='filename',
        ),
    ]
