# Generated by Django 3.2.5 on 2021-07-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appModelForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='desc',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
